__copyright__ = "Copyright (C) 2020 Nidhal Baccouri"


OPEN_AI_ENV_VAR = "OPEN_API_KEY"
DEEPL_ENV_VAR = "DEEPL_API_KEY"
LIBRE_ENV_VAR = "LIBRE_API_KEY"
MSFT_ENV_VAR = "MICROSOFT_API_KEY"
QCRI_ENV_VAR = "QCRI_API_KEY"
YANDEX_ENV_VAR = "YANDEX_API_KEY"
BAIDU_APPID_ENV_VAR = "BAIDU_APPID"
BAIDU_APPKEY_ENV_VAR = "BAIDU_APPKEY"


BASE_URLS = {
    "GOOGLE_TRANSLATE": "https://translate.google.com/m",
    "PONS": "https://en.pons.com/text-translation",
    "YANDEX": "https://translate.yandex.net/api/{version}/tr.json/{endpoint}",
    "LINGUEE": "https://www.linguee.com/",
    "MYMEMORY": "http://api.mymemory.translated.net/get",
    "QCRI": "https://mt.qcri.org/api/v1/{endpoint}?",
    "DEEPL": "https://api.deepl.com/{version}/",
    "DEEPL_FREE": "https://api-free.deepl.com/{version}/",
    "MICROSOFT_TRANSLATE": "https://api.cognitive.microsofttranslator.com/translate?api-version=3.0",
    "PAPAGO": "https://papago.naver.com/",
    "PAPAGO_API": "https://openapi.naver.com/v1/papago/n2mt",
    "LIBRE": "https://libretranslate.com/",
    "LIBRE_FREE": "https://libretranslate.de/",
    "BAIDU": "https://fanyi-api.baidu.com/api/trans/vip/translate",
}

GOOGLE_LANGUAGES_TO_CODES = {
    "abkhaz": "abx",
    "acehnese": "ace",
    "acholi": "ach",
    "afar": "aar",
    "afrikaans": "af",
    "albanian": "sq",
    "alur": "alr",
    "amharic": "am",
    "arabic": "ar",
    "armenian": "hy",
    "assamese": "as",
    "avar": "avr",
    "awadhi": "awa",
    "aymara": "ay",
    "azerbaijani": "az",
    "balinese": "ban",
    "baluchi": "bal",
    "bambara": "bm",
    "baoule": "bxe",
    "bashkir": "bas",
    "basque": "eu",
    "batak karok": "btx",
    "batak simalungun": "bts",
    "batak toba": "bbc",
    "belarusian": "be",
    "bemba": "bem",
    "bengali": "bn",
    "betawi": "bew",
    "bhojpuri": "bho",
    "bikol": "bik",
    "bosnian": "bs",
    "breton": "bre",
    "bulgarian": "bg",
    "buryat": "bur",
    "cantonese": "yue",
    "catalan": "ca",
    "cebuano": "ceb",
    "chamorro": "cha",
    "chechen": "che",
    "chichewa": "ny",
    "chinese (simplified)": "zh-CN",
    "chinese (traditional)": "zh-TW",
    "chuukese": "chu",
    "chuvash": "chv",
    "corsican": "co",
    "crimean tatar": "crh",
    "croatian": "hr",
    "czech": "cs",
    "danish": "da",
    "dari": "prs",
    "dhivehi": "dv",
    "dinka": "din",
    "dogri": "doi",
    "dombe": "dom",
    "dutch": "nl",
    "dyula": "dyu",
    "dzongkha": "dz",
    "english": "en",
    "esperanto": "eo",
    "estonian": "et",
    "ewe": "ee",
    "faroese": "fo",
    "fijian": "fij",
    "filipino": "tl",
    "finnish": "fi",
    "fon": "fon",
    "french": "fr",
    "friulian": "fur",
    "frisian": "fy",
    "fulani": "ful",
    "gaewe": "hka",
    "galician": "gl",
    "georgian": "ka",
    "german": "de",
    "greek": "el",
    "guarani": "gn",
    "gujarati": "gu",
    "haitian creole": "ht",
    "hakha chin": "hka",
    "hausa": "ha",
    "hawaiian": "haw",
    "hebrew": "iw",
    "hiligaynon": "hlg",
    "hindi": "hi",
    "hmong": "hmn",
    "hungarian": "hu",
    "hunsrik": "hrs",
    "iban": "iba",
    "icelandic": "is",
    "igbo": "ig",
    "ilocano": "ilo",
    "indonesian": "id",
    "irish": "ga",
    "italian": "it",
    "jamaican patois": "jam",
    "japanese": "ja",
    "javanese": "jw",
    "jingpo": "jpn",
    "kalaallisut": "kal",
    "kannada": "kn",
    "kanuri": "kan",
    "kazakh": "kk",
    "khasi": "kha",
    "khmer": "km",
    "kiga": "cgg",
    "kikongo": "kik",
    "kinyarwanda": "rw",
    "kituba": "kit",
    "kokborok": "kok",
    "komi": "kom",
    "konkani": "gom",
    "korean": "ko",
    "krio": "kri",
    "kurdish (kurmanji)": "ku",
    "kurdish (sorani)": "ckb",
    "kyrgyz": "ky",
    "lao": "lo",
    "latgalian": "ltg",
    "latin": "la",
    "latvian": "lv",
    "ligurian": "lij",
    "limburgish": "lim",
    "lingala": "ln",
    "lithuanian": "lt",
    "lombard": "lomb",
    "luganda": "lg",
    "luo": "luo",
    "luxembourgish": "lb",
    "macedonian": "mk",
    "madurese": "mad",
    "maithili": "mai",
    "makassar": "mak",
    "malagasy": "mg",
    "malay": "ms",
    "malay (jawi)": "jav",
    "malayalam": "ml",
    "maltese": "mt",
    "mamma": "man",
    "manx": "glv",
    "maori": "mi",
    "marathi": "mr",
    "marshallese": "msh",
    "marwadi": "mwr",
    "mauritian creole": "mrc",
    "meadow mari": "mhr",
    "meiteilon (manipuri)": "mni-Mtei",
    "minang": "min",
    "mizo": "lus",
    "mongolian": "mn",
    "myanmar": "my",
    "nahuatl (eastern huasteca)": "nah",
    "ndau": "nds",
    "ndebele (south)": "nds",
    "nepalbhasa (newari)": "new",
    "nepali": "ne",
    "nkonk": "pn",
    "norwegian": "no",
    "nuer": "nue",
    "occitan": "occ",
    "odia (oriya)": "or",
    "oromo": "om",
    "ossetian": "oss",
    "pangasinan": "pag",
    "papiamento": "pap",
    "pashto": "ps",
    "persian": "fa",
    "polish": "pl",
    "portuguese": "pt",
    "portuguese (portugal)": "pt",
    "punjabi": "pa",
    "punjabi (shahmukhi)": "pnb",
    "q'eqchi'": "kek",
    "quechua": "qu",
    "romani": "rom",
    "romanian": "ro",
    "rundi": "run",
    "russian": "ru",
    "sami (north)": "sme",
    "samoan": "sm",
    "sango": "sng",
    "sanskrit": "sa",
    "santali": "san",
    "scots gaelic": "gd",
    "sepedi": "nso",
    "serbian": "sr",
    "sesotho": "st",
    "seychellois creole": "cre",
    "shan": "shn",
    "shona": "sn",
    "sicilian": "sic",
    "silesian": "sls",
    "sindhi": "sd",
    "sinhala": "si",
    "slovak": "sk",
    "slovenian": "sl",
    "somali": "so",
    "spanish": "es",
    "sundanese": "su",
    "susu": "sus",
    "swahili": "sw",
    "swati": "sw",
    "swedish": "sv",
    "tahitian": "tyv",
    "tajik": "tg",
    "tamazight": "ber",
    "tamazight (tifinagh)": "tif",
    "tamil": "ta",
    "tatar": "tt",
    "telugu": "te",
    "tetum": "tet",
    "thai": "th",
    "tibetan": "bod",
    "tigrinya": "ti",
    "tiv": "tiv",
    "tok pisin": "tpi",
    "tongan": "ton",
    "tsonga": "ts",
    "tswana": "tsn",
    "tulu": "tcy",
    "tumbuka": "tum",
    "turkish": "tr",
    "turkmen": "tk",
    "tuvan": "tyv",
    "twi": "ak",
    "udmurt": "udm",
    "ukrainian": "uk",
    "urdu": "ur",
    "uyghur": "ug",
    "uzbek": "uz",
    "venda": "ven",
    "venetian": "vec",
    "vietnamese": "vi",
    "waray": "war",
    "welsh": "cy",
    "wolof": "wo",
    "xhosa": "xh",
    "yakut": "sah",
    "yiddish": "yi",
    "yoruba": "yo",
    "yucatec maya": "yua",
    "zapotec": "zap",
    "zulu": "zu"
}

PONS_CODES_TO_LANGUAGES = {
    "arabic": "ar",
    "bulgarian": "bg",
    "chinese": "zh-cn",
    "czech": "cs",
    "danish": "da",
    "dutch": "nl",
    "english": "en",
    "french": "fr",
    "german": "de",
    "greek": "el",
    "hungarian": "hu",
    "italian": "it",
    "latin": "la",
    "norwegian": "no",
    "polish": "pl",
    "portuguese": "pt",
    "russian": "ru",
    "slovenian": "sl",
    "spanish": "es",
    "swedish": "sv",
    "turkish": "tr",
    "elvish": "elv",
    "finnish": "fi",
    "japanese": "ja",
    "korean": "ko",
    "thai": "th",
    "vietnamese": "vi",
    "ukrainian": "uk",
    "serbian": "sr",
    "romanian": "ro",
    "persian": "fa",
    "korean": "ko",
    "indonesian": "id"
}

LINGUEE_LANGUAGES_TO_CODES = {
    "maltese": "maltese",
    "english": "english",
    "german": "german",
    "bulgarian": "bulgarian",
    "polish": "polish",
    "portuguese": "portuguese",
    "hungarian": "hungarian",
    "romanian": "romanian",
    "russian": "russian",
    # "serbian": "sr",
    "dutch": "dutch",
    "slovakian": "slovakian",
    "greek": "greek",
    "slovenian": "slovenian",
    "danish": "danish",
    "italian": "italian",
    "spanish": "spanish",
    "finnish": "finnish",
    "chinese": "chinese",
    "french": "french",
    # "croatian": "hr",
    "czech": "czech",
    "laotian": "laotian",
    "swedish": "swedish",
    "latvian": "latvian",
    "estonian": "estonian",
    "japanese": "japanese",
}

MY_MEMORY_LANGUAGES_TO_CODES = {
    "acehnese": "ace-ID",
    "afrikaans": "af",
    "albanian": "sq",
    "amharic": "am",
    "arabic": "ar",
    "armenian": "hy",
    "assamese": "as",
    "aymara": "ay",
    "azerbaijani": "az",
    "bambara": "bm",
    "balinese": "ban-ID",
    "banjar": "bjn-ID",
    "basque": "eu",
    "belarusian": "be",
    "bengali": "bn",
    "bhojpuri": "bho",
    "bosnian": "bs",
    "bulgarian": "bg",
    "buginese": "bug-ID",
    "catalan": "ca",
    "cebuano": "ceb",
    "chichewa": "ny",
    "chinese simplified": "zh-CN",
    "chinese trad. (hong kong)": "zh-HK",
    "chinese traditional": "zh-TW",
    "chinese traditional macau": "zh-MO",
    "corsican": "co",
    "croatian": "hr",
    "czech": "cs",
    "danish": "da",
    "dhivehi": "dv",
    "dogri": "doi",
    "dutch": "nl",
    "english": "en",
    "esperanto": "eo",
    "estonian": "et",
    "ewe": "ee",
    "filipino": "tl",
    "finnish": "fi",
    "french": "fr",
    "frisian": "fy",
    "galician": "gl",
    "georgian": "ka",
    "german": "de",
    "greek": "el",
    "guarani": "gn",
    "gujarati": "gu",
    "haitian creole": "ht",
    "hausa": "ha",
    "hawaiian": "haw",
    "hebrew": "iw",
    "hindi": "hi",
    "hmong": "hmn",
    "hungarian": "hu",
    "icelandic": "is",
    "igbo": "ig",
    "ilocano": "ilo",
    "indonesian": "id",
    "irish": "ga",
    "italian": "it",
    "japanese": "ja",
    "javanese": "jv-ID",
    "kannada": "kn",
    "kazakh": "kk",
    "khmer": "km",
    "kinyarwanda": "rw",
    "konkani": "gom",
    "korean": "ko",
    "krio": "kri",
    "kurdish (kurmanji)": "ku",
    "kurdish (sorani)": "ckb",
    "kyrgyz": "ky",
    "lao": "lo",
    "latin": "la",
    "latvian": "lv",
    "lingala": "ln",
    "lithuanian": "lt",
    "luganda": "lg",
    "luxembourgish": "lb",
    "macedonian": "mk",
    "maithili": "mai",
    "malagasy": "mg",
    "malay": "ms",
    "malayalam": "ml",
    "maltese": "mt",
    "maori": "mi",
    "marathi": "mr",
    "mizo": "lus",
    "mongolian": "mn",
    "myanmar": "my",
    "nepali": "ne",
    "norwegian": "no",
    "odia": "or",
    "oromo": "om",
    "pashto": "ps",
    "persian": "fa",
    "polish": "pl",
    "portuguese": "pt",
    "punjabi": "pa",
    "quechua": "qu",
    "romanian": "ro",
    "russian": "ru",
    "samoan": "sm",
    "sanskrit": "sa",
    "scots gaelic": "gd",
    "sepedi": "nso",
    "serbian": "sr",
    "sesotho": "st",
    "shona": "sn",
    "sindhi": "sd",
    "sinhala": "si",
    "slovak": "sk",
    "slovenian": "sl",
    "somali": "so",
    "spanish": "es",
    "swahili": "sw",
    "swedish": "sv",
    "tajik": "tg",
    "tamil": "ta",
    "tatar": "tt",
    "telugu": "te",
    "thai": "th",
    "tigrinya": "ti",
    "tsonga": "ts",
    "turkish": "tr",
    "turkmen": "tk",
    "twi": "tw",
    "ukrainian": "uk",
    "urdu": "ur",
    "uyghur": "ug",
    "uzbek": "uz",
    "vietnamese": "vi",
    "welsh": "cy",
    "xhosa": "xh",
    "yiddish": "yi",
    "yoruba": "yo",
    "zulu": "zu",
}

DEEPL_LANGUAGE_TO_CODE = {
    "bulgarian": "bg",
    "czech": "cs",
    "danish": "da",
    "german": "de",
    "greek": "el",
    "english": "en",
    "spanish": "es",
    "estonian": "et",
    "finnish": "fi",
    "french": "fr",
    "hungarian": "hu",
    "indonesian": "id",
    "italian": "it",
    "japanese": "ja",
    "lithuanian": "lt",
    "latvian": "lv",
    "dutch": "nl",
    "polish": "pl",
    "portuguese": "pt",
    "romanian": "ro",
    "russian": "ru",
    "slovak": "sk",
    "slovenian": "sl",
    "swedish": "sv",
    "turkish": "tr",
    "ukrainian": "uk",
    "chinese": "zh",
}

PAPAGO_LANGUAGE_TO_CODE = {
    "ko": "Korean",
    "en": "English",
    "ja": "Japanese",
    "zh-CN": "Chinese",
    "zh-TW": "Chinese traditional",
    "es": "Spanish",
    "fr": "French",
    "vi": "Vietnamese",
    "th": "Thai",
    "id": "Indonesia",
}

QCRI_LANGUAGE_TO_CODE = {"Arabic": "ar", "English": "en", "Spanish": "es"}

LIBRE_LANGUAGES_TO_CODES = {
    "English": "en",
    "Arabic": "ar",
    "Chinese": "zh",
    "French": "fr",
    "German": "de",
    "Hindi": "hi",
    "Indonesian": "id",
    "Irish": "ga",
    "Italian": "it",
    "Japanese": "ja",
    "Korean": "ko",
    "Polish": "pl",
    "Portuguese": "pt",
    "Russian": "ru",
    "Spanish": "es",
    "Turkish": "tr",
    "Vietnamese": "vi",
}

BAIDU_LANGUAGE_TO_CODE = {
    "arabic": "ara",
    "bulgarian": "bul",
    "chinese (classical)": "wyw",
    "chinese (simplified)": "zh",
    "chinese (traditional)": "cht",
    "czech": "cs",
    "danish": "dan",
    "dutch": "nl",
    "english": "en",
    "estonian": "est",
    "finnish": "fin",
    "french": "fra",
    "german": "de",
    "greek": "el",
    "hungarian": "hu",
    "italian": "it",
    "japanese": "jp",
    "korean": "kor",
    "polish": "pl",
    "portuguese": "pt",
    "romanian": "ro",
    "russian": "ru",
    "slovenian": "slo",
    "spanish": "spa",
    "swedish": "swe",
    "thai": "th",
    "vietnamese": "vie",
    "yueyu": "yue",
}
